server:
  port: 9595


spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices-security-service
    username: postgres
    password: Dhanesh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


